quotes = {
    'LIFESTYLE AND WELLNESS':["The greatest glory in living lies not in never falling, but in rising every time we fall. -Nelson Mandela","The way to get started is to quit talking and begin doing. -Walt Disney","Your time is limited, so don't waste it living someone else's life. Don't be trapped by dogma – which is living with the results of other people's thinking. -Steve Jobs","If life were predictable it would cease to be life, and be without flavor. -Eleanor Roosevelt","If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough. -Oprah Winfrey","If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success. -James Cameron","Life is what happens when you're busy making other plans. -John Lennon"],
    'POLITICS':['One of the penalties for refusing to participate in politics is that you end up being governed by your inferiors. ~Plato'],
    'SCIENCE AND TECH':["The intelligent use of science and technology are the tools with which to achieve a new direction. ~ Jacque Fresco","Science and technology can solve all the world's problems, and historically it has been shown to make the world better and better. ~ Zoltan Istvan","The science of today is the technology of tomorrow. ~ Edward Teller","Science can never solve one problem without raising ten more problems. ~ George Bernard Shaw","One machine can do the work of fifty ordinary men. No machine can do the work of one extraordinary man. ~ Elbert Hubbard","The saddest aspect of life right now is that science gathers knowledge faster than society gathers wisdom. ~ Isaac Asimov","It has become appallingly obvious that our technology has exceeded our humanity. ~ Albert Einstein"],
    'ENVIRONMENT':["I only feel angry when I see waste. When I see people throwing away things we could use. ~Mother Teresa","The Earth is what we all have in common. ~Wendell Berry","Progress is impossible without change, and those who cannot change their minds cannot change anything. ~George Bernard Shaw","Time spent among trees is never time wasted. ~Anonymous"],
    'WORLDNEWS':["When it comes to world news, attitude is what marks the distinction between justice and vengeance. Justice is pure, but vengeance brings more ruin. ~Criss Jami, Killosophy"],
    'GENERAL':["You are great! Believe in yourself"],
    'MISC':["You are great! Believe in yourself"],
    'PARENTING AND EDUCATION':["You are great! Believe in yourself","Learning never stops"],
    'EMPOWERED VOICES':["History has shown us that courage can be contagious, and hope can take on a life of its own. ~Michelle Obama","The cost of liberty is less than the price of repression. ~W.E.B. Du Bois","Education is the most powerful weapon which you can use to change the world. ~Nelson Mandela","You can't separate peace from freedom because no one can be at peace unless he has his freedom. ~Malcolm X","If there is no struggle, there is no progress. ~Frederick Douglass"],
    'SPORTS AND ENTERTAINMENT':["The only one who can tell you 'you can't win' is you and you don't have to listen. ~Jessica Ennis-Hill","I'd rather regret the risks that didn't work out than the chances I didn't take at all. ~Simone Biles","The only way to prove that you're a good sport is to lose. ~Ernie Banks","One man practicing sportsmanship is far better than 50 preaching it. ~Knute Rockne"],
    'TRAVEL-TOURISM & ART-CULTURE':["While drawing I discover what I really want to say. ~Dario Fo","If people only knew how hard I work to gain my mastery. It wouldn't seem so wonderful at all. ~Michelangelo","Art is a line around your thoughts. ~Gustav Klimt","Inspiration is for amateurs. The rest of us just show up and get the work done. If you wait around for the clouds to part and a bolt of lightning to strike you in the brain, you're not going to make an awful lot of work. ~Chuck Close"],
    'BUSINESS-MONEY':["Money is a terrible master but an excellent servant. ~P.T. Barnum","A man who pays his bills on time is soon forgotten. ~Oscar Wilde","The most difficult thing is the decision to act, the rest is merely tenacity. ~Amelia Earhart","Beware of little expenses; a small leak will sink a great ship. ~Benjamin Franklin"],
}